### ISSUE TITLE
Windows: Running "npm run build" throws "Trace: Error: Path method found without an operationId: get:\invoice"

### ISSUE THREAD

**Issue by intelman10c** [johndcarmichael/boats#16]
When running the command "npm run build" on Windows in the Visual Studio Code integrated Terminal (node v12.18.2; boats version 1.18.5), the following error appears:
`Trace: Error: Path method found without an operationId: get:\invoice
    at UniqueOperationIds.checkOpIdsAreAllUnique (C:\Users\michael.intelmann\dev\mlc-ofp-backend-swagger\node_modules\boats\build\src\UniqueOperationIds.js:71:31)
    at Object.exports.default (C:\Users\michael.intelmann\dev\mlc-ofp-backend-swagger\node_modules\boats\build\src\bundlerSwaggerParse.js:29:38)
    at async parseCli (C:\Users\michael.intelmann\dev\mlc-ofp-backend-swagger\node_modules\boats\build\src\cli.js:39:31)
    at catchHandle (C:\Users\michael.intelmann\dev\mlc-ofp-backend-swagger\node_modules\boats\build\src\cli.js:44:13)`

First assumption is the double-colon at the beginning of the output and missing "operationId": see attachment
![image](https://user-images.githubusercontent.com/26597520/89197681-64c5d780-d5ac-11ea-90ba-4388ddbe7986.png)

On Ubuntu or on Ubuntu WSL sub-system the error is not thrown and everything works fine.

**Comment by johndcarmichael** [comment]
I'm actually not a windows user and don't have enough spare time to get this windows path related issue. If anyone out there using this on windows (not in the linux sub system) is able to replicate this and offer a helping hand that would be very much appreciated.

**Comment by p-mcgowan** [comment]
@intelman10c [this merge](https://github.com/johndcarmichael/boats/pull/30) may resolve the issue - it would be cool to support windows in vscode terminal out of the box. If we had a sample repo where it fails, I could test on a windows machine, otherwise if you still use non-WSL it would be great if this fixes the issue
